// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEnvironment(arg1, arg2) {
  return window['go']['main']['App']['AddEnvironment'](arg1, arg2);
}

export function BatchUninstall(arg1) {
  return window['go']['main']['App']['BatchUninstall'](arg1);
}

export function BrowseForDirectory() {
  return window['go']['main']['App']['BrowseForDirectory']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetCleanupInfo() {
  return window['go']['main']['App']['GetCleanupInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetInstalledPackages() {
  return window['go']['main']['App']['GetInstalledPackages']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetOutdatedPackages() {
  return window['go']['main']['App']['GetOutdatedPackages']();
}

export function GetPipEnvironmentInfo() {
  return window['go']['main']['App']['GetPipEnvironmentInfo']();
}

export function GetPythonInfo() {
  return window['go']['main']['App']['GetPythonInfo']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallPackage(arg1) {
  return window['go']['main']['App']['InstallPackage'](arg1);
}

export function ListEnvironments() {
  return window['go']['main']['App']['ListEnvironments']();
}

export function MarkTourSeen() {
  return window['go']['main']['App']['MarkTourSeen']();
}

export function RemoveEnvironment(arg1) {
  return window['go']['main']['App']['RemoveEnvironment'](arg1);
}

export function RunCleanup(arg1) {
  return window['go']['main']['App']['RunCleanup'](arg1);
}

export function RunDoctor() {
  return window['go']['main']['App']['RunDoctor']();
}

export function ScanForVenvs(arg1) {
  return window['go']['main']['App']['ScanForVenvs'](arg1);
}

export function SearchPackages(arg1) {
  return window['go']['main']['App']['SearchPackages'](arg1);
}

export function SetActiveEnvironment(arg1) {
  return window['go']['main']['App']['SetActiveEnvironment'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function UninstallPackage(arg1) {
  return window['go']['main']['App']['UninstallPackage'](arg1);
}

export function UpgradePackage(arg1) {
  return window['go']['main']['App']['UpgradePackage'](arg1);
}
