// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInstalledPackages() {
  return window['go']['main']['App']['GetInstalledPackages']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallPackage(arg1) {
  return window['go']['main']['App']['InstallPackage'](arg1);
}

export function UninstallPackage(arg1) {
  return window['go']['main']['App']['UninstallPackage'](arg1);
}

export function UpgradePackage(arg1) {
  return window['go']['main']['App']['UpgradePackage'](arg1);
}
