// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pip} from '../models';

export function BatchUninstall(arg1:Array<string>):Promise<Record<string, string>>;

export function ClearHistory():Promise<void>;

export function GetCleanupInfo():Promise<pip.CleanupInfo>;

export function GetConfig():Promise<pip.AppConfig>;

export function GetHistory():Promise<Array<pip.HistoryEntry>>;

export function GetInstalledPackages():Promise<Array<pip.PipPackage>>;

export function GetLogs():Promise<Array<pip.LogEntry>>;

export function GetOutdatedPackages():Promise<Array<pip.OutdatedPackage>>;

export function GetPipEnvironmentInfo():Promise<pip.PipEnvironmentInfo>;

export function GetPythonInfo():Promise<pip.PythonInfo>;

export function Greet(arg1:string):Promise<string>;

export function InstallPackage(arg1:string):Promise<void>;

export function RunCleanup(arg1:Array<string>):Promise<void>;

export function RunDoctor():Promise<pip.DoctorReport>;

export function SearchPackages(arg1:string):Promise<Array<pip.SearchResult>>;

export function SetTheme(arg1:string):Promise<void>;

export function UninstallPackage(arg1:string):Promise<void>;

export function UpgradePackage(arg1:string):Promise<void>;
